"""Seed content for Mexican Spanish curriculum.

Each item includes:
- skill_requirements: Min skill levels (1-5) needed to attempt this item
- skill_contributions: Target skill levels this item develops when mastered
- cefr_level: CEFR level (A1, A2, B1, B2, C1, C2)
- prompt_types: Types of prompts suitable for this item

Skill levels (1-5):
1-NONE: No exposure
2-EXPOSURE: Has seen/heard
3-RECOGNITION: Can understand, can't produce
4-PRODUCTION: Can produce with effort
5-FLUENT: Automatic production
"""

from span.db.models import ContentType, CurriculumItem


SEED_CONTENT: list[CurriculumItem] = [
    # === GREETINGS (difficulty 1) ===
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Qué onda?",
        english="What's up?",
        example_sentence="¿Qué onda, güey? ¿Cómo estás?",
        mexican_notes="Very casual Mexican greeting. Use with friends.",
        topic="greetings",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},  # Entry-level, no prerequisites
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Qué pasó?",
        english="What happened? / What's up?",
        example_sentence="¡Hola! ¿Qué pasó?",
        mexican_notes="Casual way to say 'what's up' in Mexico.",
        topic="greetings",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 2,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Mande?",
        english="Pardon? / Yes?",
        example_sentence="—Te hablo. —¿Mande?",
        mexican_notes="Uniquely Mexican. Used instead of '¿Qué?' which is considered rude.",
        topic="greetings",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 4,  # High pragmatic value - knowing when to use this
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Bueno?",
        english="Hello? (on phone)",
        example_sentence="¿Bueno? Sí, él habla.",
        mexican_notes="How Mexicans answer the phone. Other countries say '¿Aló?' or '¿Diga?'",
        topic="greetings",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Mucho gusto",
        english="Nice to meet you",
        example_sentence="Hola, soy María. —Mucho gusto, soy Juan.",
        mexican_notes="Standard polite greeting when meeting someone.",
        topic="greetings",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production"],
    ),

    # === COMMON EXPRESSIONS (difficulty 1-2) ===
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¡No manches!",
        english="No way! / You're kidding!",
        example_sentence="¿Te ganaste la lotería? ¡No manches!",
        mexican_notes="Very Mexican expression of surprise. Mild euphemism.",
        topic="expressions",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={"vocabulary_recognition": 2},  # Should know some basics first
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 4,
            "conversational_flow": 2,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¡Qué padre!",
        english="How cool! / Awesome!",
        example_sentence="¿Fuiste a Cancún? ¡Qué padre!",
        mexican_notes="'Padre' means 'cool' in Mexican Spanish. Very common.",
        topic="expressions",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={"vocabulary_recognition": 2},
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Sale",
        english="Okay / Alright / Deal",
        example_sentence="—¿Nos vemos a las 8? —Sale.",
        mexican_notes="Very casual way to agree. Like 'sounds good'.",
        topic="expressions",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},
        skill_contributions={
            "vocabulary_production": 3,
            "conversational_flow": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¡Órale!",
        english="Wow! / Come on! / Alright!",
        example_sentence="¡Órale, vámonos!",
        mexican_notes="Multi-purpose expression. Can show surprise, agreement, or encouragement.",
        topic="expressions",
        difficulty=1,
        cefr_level="A1",
        skill_requirements={},
        skill_contributions={
            "vocabulary_production": 3,
            "cultural_pragmatics": 4,
            "conversational_flow": 3,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Neta",
        english="Really / For real / Truth",
        example_sentence="¿Neta? No te creo.",
        mexican_notes="Mexican slang for 'truth' or 'really'. 'La neta' = the truth.",
        topic="expressions",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3, "cultural_pragmatics": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Chido/Chida",
        english="Cool / Nice",
        example_sentence="Tu carro está muy chido.",
        mexican_notes="Mexican slang for 'cool'. Informal.",
        topic="expressions",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Güey",
        english="Dude / Bro",
        example_sentence="¿Qué onda, güey?",
        mexican_notes="Very common among friends. Can be offensive if used with strangers.",
        topic="expressions",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"cultural_pragmatics": 2},  # Need to know when appropriate
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),

    # === TEXTING ABBREVIATIONS (difficulty 2) ===
    CurriculumItem(
        content_type=ContentType.TEXTING,
        spanish="k",
        english="que (what/that)",
        example_sentence="k onda = ¿Qué onda?",
        mexican_notes="Very common texting shorthand.",
        topic="texting",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_recognition": 4,
            "vocabulary_production": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.TEXTING,
        spanish="xq / xk",
        english="porque / por qué (because / why)",
        example_sentence="xq no vienes? = ¿Por qué no vienes?",
        mexican_notes="X sounds like 'por' in Spanish pronunciation rules.",
        topic="texting",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_recognition": 4,
            "vocabulary_production": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.TEXTING,
        spanish="tb / tmb",
        english="también (also)",
        example_sentence="Yo tb quiero ir = Yo también quiero ir",
        mexican_notes="Common abbreviation in texts.",
        topic="texting",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_recognition": 4,
            "vocabulary_production": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.TEXTING,
        spanish="tkm",
        english="te quiero mucho (I love you)",
        example_sentence="Cuídate, tkm!",
        mexican_notes="Very common in affectionate messages.",
        topic="texting",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3, "cultural_pragmatics": 2},
        skill_contributions={
            "vocabulary_recognition": 4,
            "vocabulary_production": 3,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.TEXTING,
        spanish="ntp",
        english="no te preocupes (don't worry)",
        example_sentence="ntp, yo lo hago",
        mexican_notes="Casual reassurance in texts.",
        topic="texting",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_recognition": 4,
            "vocabulary_production": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.TEXTING,
        spanish="q tal",
        english="qué tal (how's it going)",
        example_sentence="Hola! Q tal?",
        mexican_notes="Common greeting in text messages.",
        topic="texting",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_recognition": 4,
            "vocabulary_production": 3,
        },
        prompt_types=["recognition", "production"],
    ),

    # === FILLER WORDS (difficulty 2) ===
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="este...",
        english="um... / uh...",
        example_sentence="Pues, este... no sé qué decir.",
        mexican_notes="Natural filler word. Makes speech sound more native.",
        topic="fillers",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 2},
        skill_contributions={
            "conversational_flow": 4,
            "pronunciation": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="o sea",
        english="I mean / like / in other words",
        example_sentence="O sea, no es que no quiera, pero...",
        mexican_notes="Very common filler. Can be overused by native speakers too!",
        topic="fillers",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 2, "conversational_flow": 2},
        skill_contributions={
            "conversational_flow": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="pues",
        english="well / so / then",
        example_sentence="Pues, vamos a ver.",
        mexican_notes="Universal Mexican filler. Can start almost any sentence.",
        topic="fillers",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 2},
        skill_contributions={
            "conversational_flow": 4,
        },
        prompt_types=["recognition", "production"],
    ),

    # === FOOD & RESTAURANTS (difficulty 2-3) ===
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Me trae la cuenta, por favor?",
        english="Can you bring me the check, please?",
        example_sentence="Ya terminamos. ¿Me trae la cuenta, por favor?",
        mexican_notes="Polite way to ask for the bill.",
        topic="food",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 2, "grammar_productive": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "grammar_productive": 3,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.VOCABULARY,
        spanish="antojitos",
        english="Mexican snacks/street food",
        example_sentence="Vamos por unos antojitos.",
        mexican_notes="Tacos, quesadillas, sopes, etc. 'Antojo' = craving.",
        topic="food",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.VOCABULARY,
        spanish="chela",
        english="beer",
        example_sentence="¿Quieres una chela?",
        mexican_notes="Mexican slang for 'cerveza'.",
        topic="food",
        difficulty=2,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Qué me recomienda?",
        english="What do you recommend?",
        example_sentence="Es mi primera vez aquí. ¿Qué me recomienda?",
        mexican_notes="Great phrase for restaurants. Shows politeness.",
        topic="food",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "grammar_productive": 3,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),

    # === DIRECTIONS & TRANSPORT (difficulty 3) ===
    CurriculumItem(
        content_type=ContentType.VOCABULARY,
        spanish="pesero / micro",
        english="minibus",
        example_sentence="Tomé el pesero para llegar más rápido.",
        mexican_notes="Small public buses. 'Pesero' from old peso fare. Also called 'combi'.",
        topic="transport",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Me baja en...?",
        english="Can you let me off at...?",
        example_sentence="¿Me baja en la próxima esquina?",
        mexican_notes="How to ask the driver to stop.",
        topic="transport",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "grammar_productive": 3,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Cuánto me cobra?",
        english="How much do you charge me?",
        example_sentence="¿Cuánto me cobra al centro?",
        mexican_notes="Use for taxis, Uber, services. More natural than '¿Cuánto cuesta?'",
        topic="transport",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "grammar_productive": 3,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),

    # === NUMBERS & MONEY (difficulty 3) ===
    CurriculumItem(
        content_type=ContentType.VOCABULARY,
        spanish="feria",
        english="change / coins / money",
        example_sentence="¿Tienes feria para el camión?",
        mexican_notes="Mexican slang for small change or money in general.",
        topic="money",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3, "cultural_pragmatics": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.VOCABULARY,
        spanish="lana",
        english="money (slang)",
        example_sentence="No traigo lana.",
        mexican_notes="Very common slang for money. Literally means 'wool'.",
        topic="money",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_recognition": 3, "cultural_pragmatics": 2},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿A cómo?",
        english="How much? (price)",
        example_sentence="¿A cómo los aguacates?",
        mexican_notes="Informal way to ask price at markets. Short for '¿A cómo está?'",
        topic="money",
        difficulty=3,
        cefr_level="A2",
        skill_requirements={"vocabulary_production": 3},
        skill_contributions={
            "vocabulary_production": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),

    # === STORYTELLING / NARRATION (B1) - USER PRIORITY ===
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Sabes qué pasó?",
        english="You know what happened?",
        example_sentence="¿Sabes qué pasó ayer? ¡No lo vas a creer!",
        mexican_notes="Great story opener. Creates anticipation.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 2},
        skill_contributions={
            "narration": 3,
            "conversational_flow": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Un día...",
        english="One day...",
        example_sentence="Un día estaba caminando por el centro y de repente...",
        mexican_notes="Classic story starter. Sets the scene for a narrative.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3},
        skill_contributions={
            "narration": 3,
            "grammar_productive": 3,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Primero... luego... después...",
        english="First... then... after...",
        example_sentence="Primero fui al mercado, luego compré fruta, y después fui a casa.",
        mexican_notes="Sequence markers for ordering events. Essential for clear storytelling.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 3},
        skill_contributions={
            "narration": 4,
            "grammar_productive": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="De repente...",
        english="Suddenly...",
        example_sentence="Estábamos hablando tranquilos y de repente empezó a llover.",
        mexican_notes="Creates drama and surprise in stories. Very natural in Mexican Spanish.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "narration": 2},
        skill_contributions={
            "narration": 4,
            "conversational_flow": 3,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¡No lo vas a creer!",
        english="You're not going to believe it!",
        example_sentence="¡No lo vas a creer! Me encontré a mi ex en el super.",
        mexican_notes="Builds suspense. Very common in casual storytelling.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 3},
        skill_contributions={
            "narration": 4,
            "conversational_flow": 4,
            "cultural_pragmatics": 3,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Mientras tanto...",
        english="Meanwhile...",
        example_sentence="Yo estaba en el trabajo. Mientras tanto, mi hermano llegó a mi casa.",
        mexican_notes="Links parallel events in a story. Shows sophistication.",
        topic="storytelling",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "narration": 3},
        skill_contributions={
            "narration": 5,
            "grammar_productive": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¡Fue increíble!",
        english="It was incredible!",
        example_sentence="¡Fue increíble! Nunca había visto algo así.",
        mexican_notes="Emotional punctuation for stories. Shows engagement.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3},
        skill_contributions={
            "narration": 3,
            "vocabulary_production": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Me acuerdo que...",
        english="I remember that...",
        example_sentence="Me acuerdo que era un día soleado cuando nos conocimos.",
        mexican_notes="Introduces memories and past events. Very natural opener.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 3},
        skill_contributions={
            "narration": 4,
            "grammar_productive": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Al final...",
        english="In the end...",
        example_sentence="Al final todo salió bien y nos reímos mucho.",
        mexican_notes="Story conclusion marker. Signals you're wrapping up.",
        topic="storytelling",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "narration": 2},
        skill_contributions={
            "narration": 4,
            "conversational_flow": 4,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Y así fue como...",
        english="And that's how...",
        example_sentence="Y así fue como conocí a tu madre.",
        mexican_notes="Classic story ending phrase. Creates closure.",
        topic="storytelling",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "narration": 3, "grammar_productive": 3},
        skill_contributions={
            "narration": 5,
            "conversational_flow": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),

    # === CONDITIONALS / HYPOTHETICALS (B1) - USER PRIORITY ===
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Si tengo tiempo, voy.",
        english="If I have time, I'll go.",
        example_sentence="Si tengo tiempo mañana, voy al gimnasio.",
        mexican_notes="Real conditional - something likely to happen. Present + present/future.",
        topic="conditionals",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 3},
        skill_contributions={
            "conditionals": 3,
            "grammar_productive": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Si yo fuera tú...",
        english="If I were you...",
        example_sentence="Si yo fuera tú, hablaría con él directamente.",
        mexican_notes="Hypothetical - imperfect subjunctive. Very useful for giving advice.",
        topic="conditionals",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "grammar_productive": 3, "conditionals": 2},
        skill_contributions={
            "conditionals": 4,
            "grammar_productive": 5,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Me gustaría...",
        english="I would like...",
        example_sentence="Me gustaría viajar a Oaxaca algún día.",
        mexican_notes="Polite conditional for wishes and desires. Very common.",
        topic="conditionals",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 2},
        skill_contributions={
            "conditionals": 3,
            "grammar_productive": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Si tuviera dinero, viajaría.",
        english="If I had money, I would travel.",
        example_sentence="Si tuviera más dinero, viajaría por todo México.",
        mexican_notes="Classic hypothetical structure: imperfect subjunctive + conditional.",
        topic="conditionals",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "grammar_productive": 3, "conditionals": 3},
        skill_contributions={
            "conditionals": 5,
            "grammar_productive": 5,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Ojalá pudiera...",
        english="I wish I could...",
        example_sentence="Ojalá pudiera hablar español perfectamente.",
        mexican_notes="Expresses wishes for something unlikely. 'Ojalá' from Arabic inshallah.",
        topic="conditionals",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "grammar_productive": 3, "conditionals": 2},
        skill_contributions={
            "conditionals": 4,
            "grammar_productive": 5,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="¿Qué harías si...?",
        english="What would you do if...?",
        example_sentence="¿Qué harías si ganaras la lotería?",
        mexican_notes="Great conversation starter. Opens hypothetical discussion.",
        topic="conditionals",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "grammar_productive": 3, "conditionals": 3},
        skill_contributions={
            "conditionals": 5,
            "grammar_productive": 5,
            "conversational_flow": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Si hubiera sabido...",
        english="If I had known...",
        example_sentence="Si hubiera sabido que estabas aquí, habría venido antes.",
        mexican_notes="Past hypothetical - pluperfect subjunctive. For regrets and missed opportunities.",
        topic="conditionals",
        difficulty=5,  # Max difficulty - advanced B2 grammar
        cefr_level="B2",
        skill_requirements={"vocabulary_production": 4, "grammar_productive": 4, "conditionals": 4},
        skill_contributions={
            "conditionals": 5,
            "grammar_productive": 5,
        },
        prompt_types=["recognition", "production"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Sería bueno si...",
        english="It would be good if...",
        example_sentence="Sería bueno si pudiéramos vernos más seguido.",
        mexican_notes="Polite way to make suggestions. Softens requests.",
        topic="conditionals",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 3, "conditionals": 2},
        skill_contributions={
            "conditionals": 4,
            "grammar_productive": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="En tu lugar, yo...",
        english="In your place, I would...",
        example_sentence="En tu lugar, yo le diría la verdad.",
        mexican_notes="Alternative to 'si yo fuera tú'. Common in advice-giving.",
        topic="conditionals",
        difficulty=4,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 3, "grammar_productive": 3},
        skill_contributions={
            "conditionals": 4,
            "grammar_productive": 4,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
    CurriculumItem(
        content_type=ContentType.PHRASE,
        spanish="Si pudiera, lo haría.",
        english="If I could, I would do it.",
        example_sentence="¿Me ayudarías? —Si pudiera, lo haría, pero tengo trabajo.",
        mexican_notes="Polite refusal or expression of limitation. Very useful.",
        topic="conditionals",
        difficulty=5,
        cefr_level="B1",
        skill_requirements={"vocabulary_production": 4, "grammar_productive": 3, "conditionals": 3},
        skill_contributions={
            "conditionals": 4,
            "grammar_productive": 5,
            "cultural_pragmatics": 4,
        },
        prompt_types=["recognition", "production", "application"],
    ),
]


def seed_database(db) -> int:
    """Add all seed content to the database. Returns number of items added."""
    count = 0
    for item in SEED_CONTENT:
        db.add_curriculum_item(item)
        count += 1
    return count
